// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPendingRequests() {
  return window['go']['main']['App']['GetPendingRequests']();
}

export function ResolveRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveRequest'](arg1, arg2, arg3);
}
